export const theme = {
  bgSecondary: '#68b4e6',
  bg: '#f8f4f4',
  danger: '#EA4040',
  secondary: '#fff',
  tertiary: '#EA81B6',
  textSecondary: '#898989',
  text: '#fff',
  textInverted: '#000',
  fontSizeTitle: '15',
  borderRadius: 10,
  border: '#D9D5DC',
  disabled: '#efefef',
  primary: '#68b4e6',
  icon: '#919191',
  success: '#41B791',
  warning: '#f37736'
};

export const images = {
  headset: require('../images/icons/headset.svg'),
  heart: require('../images/icons/solido-heart.svg'),
  phone: require('../images/phone.png'),
  leave: require('../images/icons/sair.svg'),
  schedule: require('../images/icons/solido-agendar.svg'),
  help: require('../images/icons/solido-ajuda.svg'),
  notService: require('../images/3.png'),
  signature: require('../images/icons/solido-assinatura.svg'),
  calendar: require('../images/icons/solido-calendar.svg'),
  card: require('../images/icons/solido-card.svg'),
  chat: require('../images/icons/solido-chat.svg'),
  checkin: require('../images/icons/solido-cheguei.svg'),
  checkout: require('../images/icons/solido-finalizar.svg'),
  gps: require('../images/icons/solido-gps.svg'),
  hour: require('../images/icons/solido-hour.svg'),
  information: require('../images/icons/solido-informacao.svg'),
  notification: require('../images/icons/solido-notification.svg'),
  productor: require('../images/icons/solido-produtos.svg'),
  clear: require('../images/5.svg'),
  home: require('../images/2.png'),
  logo: require('../images/logo.png'),
  menssage: require('../images/sms.png'),
  phoneSms: require('../images/5.svg'),
  dayJob: require('../images/1.png'),
  manual: require('../images/manual.png')
};
